const MONGODB_URL = process.env.MONGODB_URL ?? "";
const MONGODB_DB_NAME = process.env.MONGODB_DB_NAME ?? "";
const FOUNDATION_COLOR_IMMUTABLE_COLLECTION_ID = "foundation-color";
const COMPONENT_STATUS_IMMUTABLE_COLLECTION_ID = "foundation-component";

export {
  MONGODB_URL,
  MONGODB_DB_NAME,
  FOUNDATION_COLOR_IMMUTABLE_COLLECTION_ID,
  COMPONENT_STATUS_IMMUTABLE_COLLECTION_ID,
};
